# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: simon
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - riscv64
    main: ./cmd/simon

archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- .Arch  }}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    rlcp: true
    files:
      - README.md
      - LICENSE

dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "{{ .Env.IMAGE }}:{{ .Version }}-amd64"
      - "{{ .Env.IMAGE }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.description=Description"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "{{ .Env.IMAGE }}:{{ .Version }}-arm64"
      - "{{ .Env.IMAGE }}:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.description=Description"
  - use: buildx
    goos: linux
    goarch: riscv64
    # riscv64 architecture support for static images
    # https://github.com/go-riscv/distroless
    # https://github.com/GoogleContainerTools/distroless/issues/1269
    dockerfile: riscv64.Dockerfile
    image_templates:
      - "{{ .Env.IMAGE }}:{{ .Version }}-riscv64"
      - "{{ .Env.IMAGE }}:latest-riscv64"
    build_flag_templates:
      - "--platform=linux/riscv64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.description=Description"
docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: "{{ .Env.IMAGE }}:{{ .Version }}"
    image_templates:
      - "{{ .Env.IMAGE }}:{{ .Version }}-amd64"
      - "{{ .Env.IMAGE }}:{{ .Version }}-arm64"
      - "{{ .Env.IMAGE }}:{{ .Version }}-riscv64"
  - name_template: "{{ .Env.IMAGE }}:latest"
    image_templates:
      - "{{ .Env.IMAGE }}:latest-amd64"
      - "{{ .Env.IMAGE }}:latest-arm64"
      - "{{ .Env.IMAGE }}:latest-riscv64"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore(dep):'
      - '^test:'

sboms:
  - artifacts: archive

nfpms:
  - package_name: go-faster-simon
    homepage: https://github.com/go-faster/simon
    maintainer: Aleksandr Razumov <ernado@go-faster.org>
    description: Set of observability testing services
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
