openapi: 3.0.3
info:
  title: Go Faster Simon
  description: Simon API
  version: 0.1.0
servers:
  - url: 'https://localhost:8080'
paths:
  /status:
    get:
      operationId: "status"
      description: "get status"
      responses:
        200:
          description: Status
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Status"
        default:
          $ref: "#/components/responses/Error"
components:
  responses:
    Error:
      description: "Error while processing request"
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    Status:
      type: object
      properties:
        message:
          type: string
      required: [ message ]

    Error:
      type: object
      description: "error description"
      properties:
        message:
          type: string
      required: [ message ]
