apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        app.kubernetes.io/part-of: simon
        app.kubernetes.io/component: client
        service.opentelemetry.io/name: go-faster.simon.client
    spec:
      containers:
      - name: client
        image: ghcr.io/go-faster/simon:latest
        args:
          - "client"
        ports:
          - containerPort: 8090
            protocol: TCP
            name: metrics
        env:
          - name: SERVER_ADDR
            value: "http://server"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"
          - name: OTEL_METRICS_EXPORTER
            value: "prometheus"
          - name: OTEL_EXPORTER_PROMETHEUS_PORT
            value: "8090"
          - name: OTEL_EXPORTER_PROMETHEUS_HOST
            value: "0.0.0.0"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.name=go-faster.simon.client"
          - name: OTEL_LOG_LEVEL
            value: "DEBUG"
          - name: OTEL_TRACES_EXPORTER
            value: "otlp"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://tempo-distributor.monitoring.svc.cluster.local:4317"
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"