---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        app.kubernetes.io/part-of: simon
        app.kubernetes.io/component: server
        service.opentelemetry.io/name: go-faster.simon.server
    spec:
      containers:
      - name: server
        image: ghcr.io/go-faster/simon:latest
        args:
          - "server"
        ports:
          - containerPort: 8090
            protocol: TCP
            name: metrics
          - containerPort: 8080
            protocol: TCP
            name: http
        env:
          - name: HTTP_ADDR
            value: ":8080"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"
          - name: OTEL_METRICS_EXPORTER
            value: "prometheus"
          - name: OTEL_EXPORTER_PROMETHEUS_PORT
            value: "8090"
          - name: OTEL_EXPORTER_PROMETHEUS_HOST
            value: "0.0.0.0"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.name=go-faster.simon.server"
          - name: OTEL_LOG_LEVEL
            value: "DEBUG"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://tempo-distributor.monitoring.svc.cluster.local:4317"
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"