apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: server.ingress
spec:
  endpointSelector:
    matchLabels:
      app: server
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: client
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    - {}
